version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g pnpm
  pre_build:
    commands:
      - echo Build started on `date`
      - pnpm install
      - echo "Prepare env"
      - touch .env
      - echo "WEB_APP_BASE_URL=$WEB_APP_BASE_URL" >> .env
      - cat .env
  build:
    commands:
      - pnpm build
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  base-directory: dist
  files:
    - '**/*'

cache:
  paths:
    - './node_modules/**/*'