version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install -g yaml
  pre_build:
    commands:
      - echo Build started on `date`
      - yaml install
      - echo "Prepare env"
      - touch .env
      - echo "WEB_APP_BASE_URL=$WEB_APP_BASE_URL" >> .env
      - cat .env
  build:
    commands:
      - yaml build
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  base-directory: dist
  files:
    - '**/*'

#cache:
#  paths:
#    - './node_modules/**/*'